<h2>Initial steps for setup</h2>

In [1]:
#importing pandas
import pandas as pd

In [2]:
#reading the csv into pandas dataframe
textile_data=pd.read_csv('Plastic based Textiles in clothing industry.csv')

In [3]:
#first 5 rows
textile_data.head()

,Company,Product_Type,Production_Year,Greenhouse_Gas_Emissions,Pollutants_Emitted,Water_Consumption,Energy_Consumption,Waste_Generation,Sales_Revenue
0,Zara,Polyester,2020,5000,20,7500,1200,300,500000
1,Zara,Nylon,2019,3000,15,5000,900,200,450000
2,Zara,Recycled_Poly,2021,3500,18,6000,1100,250,480000
3,Zara,Cotton,2018,2000,10,4500,800,180,550000
4,Zara,Synthetic_Blend,2022,6000,25,8000,1500,350,600000

In [4]:
#number of rows in the dataset
len(textile_data)

6956

<h2> Removing Nulls & Duplicates </h2>

In [5]:
#checking to find any null values
textile_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6956 entries, 0 to 6955
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Company                   6956 non-null   object
 1   Product_Type              6956 non-null   object
 2   Production_Year           6956 non-null   int64
 3   Greenhouse_Gas_Emissions  6956 non-null   int64
 4   Pollutants_Emitted        6956 non-null   int64
 5   Water_Consumption         6956 non-null   int64
 6   Energy_Consumption        6956 non-null   int64
 7   Waste_Generation          6956 non-null   int64
 8   Sales_Revenue             6956 non-null   int64
dtypes: int64(7), object(2)
memory usage: 489.2+ KB

Looking at the columns, there are no null values in any of the columns since all of them have the same values as the number of rows

In [6]:
#confirmation of lack of null values
textile_data.isnull().sum()

Company                     0
Product_Type                0
Production_Year             0
Greenhouse_Gas_Emissions    0
Pollutants_Emitted          0
Water_Consumption           0
Energy_Consumption          0
Waste_Generation            0
Sales_Revenue               0
dtype: int64

Findings are consistent, no null values

In [7]:
#dropping duplicate rows
textile_data=textile_data[textile_data.duplicated()==False]

In [8]:
len(textile_data)

6956

No duplicate rows were found, since the number of rows in the dataset are the same

<h2> Exploring Data </h2><br>
In order to see what the distribution is like

In [9]:
#checking the range of numeric data
textile_data.describe()

,Production_Year,Greenhouse_Gas_Emissions,Pollutants_Emitted,Water_Consumption,Energy_Consumption,Waste_Generation,Sales_Revenue
count,6956.000000,6956.000000,6956.000000,6956.000000,6956.000000,6956.000000,6956.000000
mean,2020.001150,3891.252300,16.992812,5983.972542,1106.555204,248.891748,510234.839275
std,1.415026,1219.957903,4.913978,1153.555849,232.108015,57.751230,51775.324086
min,2018.000000,1800.000000,9.000000,4000.000000,700.000000,150.000000,420000.000000
25%,2019.000000,2837.750000,13.000000,5005.000000,906.000000,198.000000,465467.750000
50%,2020.000000,3876.500000,17.000000,5943.000000,1112.000000,249.000000,510494.000000
75%,2021.000000,4968.000000,21.000000,6991.250000,1308.000000,299.000000,555122.750000
max,2022.000000,6000.000000,25.000000,8000.000000,1500.000000,350.000000,600000.000000

In [10]:
company_counts=pd.DataFrame(textile_data['Company'].value_counts())
company_counts

                  count
Company
Nike               1444
Zara               1396
Urban Outfitters   1390
Adidas             1376
Forever 21         1350

In [11]:
#checking the distribution of rows amongst the companies
company_counts['Percentage_of_share']=company_counts['count']/len(textile_data)
company_counts

                  count  Percentage_of_share
Company
Nike               1444             0.207591
Zara               1396             0.200690
Urban Outfitters   1390             0.199827
Adidas             1376             0.197815
Forever 21         1350             0.194077

Each company has a similar share in the dataset, there is no disproportionate representation

<h2> Preprocessing for analysis and visualization</h2> <br>

In [12]:
#making the column names visualization friendly by removing the underscore
textile_data.columns = [colname.replace('_', ' ') for colname in textile_data.columns]
textile_data.head()

,Company,Product Type,Production Year,Greenhouse Gas Emissions,Pollutants Emitted,Water Consumption,Energy Consumption,Waste Generation,Sales Revenue
0,Zara,Polyester,2020,5000,20,7500,1200,300,500000
1,Zara,Nylon,2019,3000,15,5000,900,200,450000
2,Zara,Recycled_Poly,2021,3500,18,6000,1100,250,480000
3,Zara,Cotton,2018,2000,10,4500,800,180,550000
4,Zara,Synthetic_Blend,2022,6000,25,8000,1500,350,600000

In [13]:
#viewing product type because it has the underscore character, let's check if it has any other special characters
textile_data['Product Type'].value_counts()

Product Type
Linen              686
Organic_Cotton     673
Polyester          665
Microfiber         653
Nylon              637
Recycled_Poly      630
Viscose            623
Cotton             613
Wool               611
Tencel             583
Synthetic_Blend    582
Name: count, dtype: int64

In [14]:
#replace the underscore by a space
textile_data['Product Type']=[val.replace('_',' ') for val in textile_data['Product Type']]
textile_data.head()

,Company,Product Type,Production Year,Greenhouse Gas Emissions,Pollutants Emitted,Water Consumption,Energy Consumption,Waste Generation,Sales Revenue
0,Zara,Polyester,2020,5000,20,7500,1200,300,500000
1,Zara,Nylon,2019,3000,15,5000,900,200,450000
2,Zara,Recycled Poly,2021,3500,18,6000,1100,250,480000
3,Zara,Cotton,2018,2000,10,4500,800,180,550000
4,Zara,Synthetic Blend,2022,6000,25,8000,1500,350,600000

In [15]:
#export cleaned data to csv
textile_data.to_csv("Cleaned Dataset.csv")

<h2>Modifying Data Format for Visualization</h2>

<h3> For visualizations 1 & 2: numeric values over the years, creating a dataset containing numeric paarmeters per year for each brand, except product type</h3>

In [16]:
company_year_data=textile_data.groupby(['Production Year','Company']).sum(numeric_only=True)
company_year_data

                                  Greenhouse Gas Emissions  \
Production Year Company
2018            Adidas                             1044326
                Forever 21                         1138428
                Nike                               1168119
                Urban Outfitters                   1027296
                Zara                               1108090
2019            Adidas                             1039273
                Forever 21                         1146260
                Nike                               1137905
                Urban Outfitters                   1091130
                Zara                               1013600
2020            Adidas                             1161982
                Forever 21                         1055245
                Nike                               1073177
                Urban Outfitters                    977052
                Zara                               1090637
2021            Adidas                             1024854
                Forever 21                         1038517
                Nike                               1119962
                Urban Outfitters                   1110325
                Zara                               1127806
2022            Adidas                             1128126
                Forever 21                          915187
                Nike                               1123666
                Urban Outfitters                   1167414
                Zara                               1039174

                                  Pollutants Emitted  Water Consumption  \
Production Year Company
2018            Adidas                          4495            1598015
                Forever 21                      4812            1683287
                Nike                            5036            1724813
                Urban Outfitters                4458            1596444
                Zara                            4955            1708959
2019            Adidas                          4608            1614774
                Forever 21                      5028            1745852
                Nike                            5098            1749653
                Urban Outfitters                4713            1678043
                Zara                            4499            1585130
2020            Adidas                          4925            1729151
                Forever 21                      4481            1605209
                Nike                            4491            1624327
                Urban Outfitters                4320            1498737
                Zara                            4698            1727439
2021            Adidas                          4280            1545939
                Forever 21                      4554            1623873
                Nike                            4984            1764998
                Urban Outfitters                4915            1756492
                Zara                            5139            1784617
2022            Adidas                          4788            1657075
                Forever 21                      4006            1406138
                Nike                            5185            1813593
                Urban Outfitters                5313            1828270
                Zara                            4421            1573685

                                  Energy Consumption  Waste Generation  \
Production Year Company
2018            Adidas                        291479             68006
                Forever 21                    310153             72189
                Nike                          322613             71903
                Urban Outfitters              288829             64648
                Zara                          318237             71528
2019            Adidas                        299960             67726
                Forever 21                    330501             73609
                Nike                          331199             71891
                Urban Outfitters              311365             69264
                Zara                          291225             64243
2020            Adidas                        325937             73882
                Forever 21                    303345             66528
                Nike                          295287             65924
                Urban Outfitters              273888             62860
                Zara                          314703             70495
2021            Adidas                        291807             66332
                Forever 21                    292881             66067
                Nike                          324015             72978
                Urban Outfitters              315566             71878
                Zara                          321863             72944
2022            Adidas                        311197             69829
                Forever 21                    260588             57753
                Nike                          333589             76143
                Urban Outfitters              337069             76981
                Zara                          299902             65690

                                  Sales Revenue
Production Year Company
2018            Adidas                133652623
                Forever 21            144650668
                Nike                  149306143
                Urban Outfitters      130937736
                Zara                  145638397
2019            Adidas                138442743
                Forever 21            151774036
                Nike                  149541222
                Urban Outfitters      143944554
                Zara                  134701549
2020            Adidas                149011242
                Forever 21            137644735
                Nike                  137496343
                Urban Outfitters      127832625
                Zara                  145353050
2021            Adidas                134115030
                Forever 21            138104123
                Nike                  147602134
                Urban Outfitters      149773057
                Zara                  151009589
2022            Adidas                144345136
                Forever 21            117790701
                Nike                  153142314
                Urban Outfitters      157562548
                Zara                  135821244

In [17]:
company_year_data.to_csv('Flourish Viz 1 and 2.csv')

<h3> For visualizations 3: Relation between Product Type and Greenhouse emissions

In [18]:
product_type_data=textile_data.groupby(['Company','Product Type']).sum(numeric_only=True).drop(['Production Year','Sales Revenue'],axis=1)
product_type_data

                                  Greenhouse Gas Emissions  \
Company          Product Type
Adidas           Cotton                             439255
                 Linen                              555228
                 Microfiber                         452320
                 Nylon                              467970
                 Organic Cotton                     551349
                 Polyester                          584509
                 Recycled Poly                      480943
                 Synthetic Blend                    461289
                 Tencel                             426001
                 Viscose                            509177
                 Wool                               470520
Forever 21       Cotton                             495567
                 Linen                              482436
                 Microfiber                         584167
                 Nylon                              464166
                 Organic Cotton                     432725
                 Polyester                          487141
                 Recycled Poly                      389699
                 Synthetic Blend                    524275
                 Tencel                             409619
                 Viscose                            495677
                 Wool                               528165
Nike             Cotton                             534497
                 Linen                              560214
                 Microfiber                         494887
                 Nylon                              545651
                 Organic Cotton                     483987
                 Polyester                          540422
                 Recycled Poly                      536882
                 Synthetic Blend                    379624
                 Tencel                             476065
                 Viscose                            554971
                 Wool                               515629
Urban Outfitters Cotton                             466007
                 Linen                              585337
                 Microfiber                         462994
                 Nylon                              487725
                 Organic Cotton                     509813
                 Polyester                          500047
                 Recycled Poly                      542926
                 Synthetic Blend                    483569
                 Tencel                             473707
                 Viscose                            448935
                 Wool                               412157
Zara             Cotton                             482039
                 Linen                              456696
                 Microfiber                         535947
                 Nylon                              505957
                 Organic Cotton                     626628
                 Polyester                          483107
                 Recycled Poly                      438819
                 Synthetic Blend                    516291
                 Tencel                             478890
                 Viscose                            403912
                 Wool                               451021

                                  Pollutants Emitted  Water Consumption  \
Company          Product Type
Adidas           Cotton                         1899             631087
                 Linen                          2534             867638
                 Microfiber                     1982             680268
                 Nylon                          2021             670818
                 Organic Cotton                 2309             812275
                 Polyester                      2444             869793
                 Recycled Poly                  2031             757806
                 Synthetic Blend                1799             668253
                 Tencel                         1878             671977
                 Viscose                        2244             806401
                 Wool                           1955             708638
Forever 21       Cotton                         2103             716240
                 Linen                          2041             696259
                 Microfiber                     2402             874819
                 Nylon                          2022             753915
                 Organic Cotton                 1986             684382
                 Polyester                      2130             750165
                 Recycled Poly                  1686             594279
                 Synthetic Blend                2111             791185
                 Tencel                         1798             653813
                 Viscose                        2245             738104
                 Wool                           2357             811198
Nike             Cotton                         2298             817622
                 Linen                          2491             867441
                 Microfiber                     2219             790239
                 Nylon                          2352             837406
                 Organic Cotton                 2250             769870
                 Polyester                      2391             854342
                 Recycled Poly                  2350             801657
                 Synthetic Blend                1572             565870
                 Tencel                         2075             702421
                 Viscose                        2398             849565
                 Wool                           2398             820951
Urban Outfitters Cotton                         2059             706775
                 Linen                          2545             895632
                 Microfiber                     2191             770849
                 Nylon                          2220             802830
                 Organic Cotton                 2258             813429
                 Polyester                      2111             739285
                 Recycled Poly                  2512             844094
                 Synthetic Blend                2010             701349
                 Tencel                         2113             758965
                 Viscose                        1985             701001
                 Wool                           1715             623777
Zara             Cotton                         2137             764644
                 Linen                          2088             731832
                 Microfiber                     2284             809887
                 Nylon                          2187             757397
                 Organic Cotton                 2646             954216
                 Polyester                      2208             771440
                 Recycled Poly                  2247             731740
                 Synthetic Blend                2184             788721
                 Tencel                         2049             728711
                 Viscose                        1731             650790
                 Wool                           1951             690452

                                  Energy Consumption  Waste Generation
Company          Product Type
Adidas           Cotton                       120999             28416
                 Linen                        167505             37167
                 Microfiber                   122534             28828
                 Nylon                        132740             30073
                 Organic Cotton               148933             35591
                 Polyester                    159773             36125
                 Recycled Poly                139722             31465
                 Synthetic Blend              128688             27507
                 Tencel                       116510             26025
                 Viscose                      149888             34090
                 Wool                         133088             30488
Forever 21       Cotton                       134702             31459
                 Linen                        130659             29349
                 Microfiber                   165139             37480
                 Nylon                        138750             31044
                 Organic Cotton               126270             27856
                 Polyester                    143430             30869
                 Recycled Poly                110384             24398
                 Synthetic Blend              141714             31962
                 Tencel                       120712             26503
                 Viscose                      136561             31408
                 Wool                         149147             33818
Nike             Cotton                       147943             32282
                 Linen                        161280             34818
                 Microfiber                   141458             31951
                 Nylon                        149588             34439
                 Organic Cotton               148177             32116
                 Polyester                    154599             34883
                 Recycled Poly                151829             34621
                 Synthetic Blend              107225             24294
                 Tencel                       132410             30325
                 Viscose                      161135             35493
                 Wool                         151059             33617
Urban Outfitters Cotton                       131520             30239
                 Linen                        166582             37067
                 Microfiber                   137790             32595
                 Nylon                        143097             32431
                 Organic Cotton               143749             32619
                 Polyester                    136655             30802
                 Recycled Poly                156483             36336
                 Synthetic Blend              131513             29749
                 Tencel                       136647             30606
                 Viscose                      123682             27049
                 Wool                         118999             26138
Zara             Cotton                       142298             31702
                 Linen                        134171             30740
                 Microfiber                   146961             32454
                 Nylon                        141703             31509
                 Organic Cotton               175589             40716
                 Polyester                    142407             32356
                 Recycled Poly                142511             31627
                 Synthetic Blend              139636             30913
                 Tencel                       132109             28551
                 Viscose                      116092             25982
                 Wool                         132453             28350

In [19]:
product_type_data.to_csv('Flourish Viz 3.csv')